services:
  - type: web
    name: nyc-scraper-hybrid
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: CAPTCHA_API_KEY
        sync: false
      - key: PROXY_LIST
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./violations.db
      - key: MAX_CONCURRENT_REQUESTS
        value: 3
      - key: REQUEST_TIMEOUT
        value: 30
      - key: CACHE_DURATION
        value: 3600
      - key: NYC_API_BASE_URL
        value: https://data.cityofnewyork.us/resource/nc67-uf89.json
      - key: NYC_API_LIMIT
        value: 1000
      - key: SCRAPER_HEADLESS
        value: true
      - key: SCRAPER_TIMEOUT
        value: 60000
      - key: MAX_RETRIES
        value: 3
      - key: RATE_LIMIT_REQUESTS
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 3600
      - key: LOG_LEVEL
        value: INFO
    buildCommand: ""
    startCommand: "uvicorn hybrid_server:app --host 0.0.0.0 --port $PORT --workers 1"